# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Choice.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChoiceWindow(object):
    def setupUi(self, ChoiceWindow):
        ChoiceWindow.setObjectName("ChoiceWindow")
        ChoiceWindow.resize(547, 289)
        self.label = QtWidgets.QLabel(ChoiceWindow)
        self.label.setGeometry(QtCore.QRect(210, 30, 111, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(ChoiceWindow)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 80, 471, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonQL = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQL.sizePolicy().hasHeightForWidth())
        self.pushButtonQL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonQL.setFont(font)
        self.pushButtonQL.setDefault(True)
        self.pushButtonQL.setObjectName("pushButtonQL")
        self.horizontalLayout.addWidget(self.pushButtonQL)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonBH = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBH.sizePolicy().hasHeightForWidth())
        self.pushButtonBH.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonBH.setFont(font)
        self.pushButtonBH.setObjectName("pushButtonBH")
        self.horizontalLayout.addWidget(self.pushButtonBH)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonZQ = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonZQ.sizePolicy().hasHeightForWidth())
        self.pushButtonZQ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonZQ.setFont(font)
        self.pushButtonZQ.setObjectName("pushButtonZQ")
        self.horizontalLayout.addWidget(self.pushButtonZQ)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButtonXW = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonXW.sizePolicy().hasHeightForWidth())
        self.pushButtonXW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonXW.setFont(font)
        self.pushButtonXW.setObjectName("pushButtonXW")
        self.horizontalLayout.addWidget(self.pushButtonXW)
        self.label_2 = QtWidgets.QLabel(ChoiceWindow)
        self.label_2.setGeometry(QtCore.QRect(171, 211, 192, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(ChoiceWindow)
        self.widget.setGeometry(QtCore.QRect(50, 180, 431, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEditRight = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditRight.sizePolicy().hasHeightForWidth())
        self.lineEditRight.setSizePolicy(sizePolicy)
        self.lineEditRight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditRight.setObjectName("lineEditRight")
        self.horizontalLayout_2.addWidget(self.lineEditRight)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEditWrong = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditWrong.sizePolicy().hasHeightForWidth())
        self.lineEditWrong.setSizePolicy(sizePolicy)
        self.lineEditWrong.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditWrong.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditWrong.setObjectName("lineEditWrong")
        self.horizontalLayout_2.addWidget(self.lineEditWrong)
        spacerItem4 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.Score = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Score.setFont(font)
        self.Score.setObjectName("Score")
        self.horizontalLayout_2.addWidget(self.Score)
        self.lineEditScore = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditScore.sizePolicy().hasHeightForWidth())
        self.lineEditScore.setSizePolicy(sizePolicy)
        self.lineEditScore.setMaximumSize(QtCore.QSize(80, 100))
        self.lineEditScore.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditScore.setCursorPosition(0)
        self.lineEditScore.setReadOnly(False)
        self.lineEditScore.setObjectName("lineEditScore")
        self.horizontalLayout_2.addWidget(self.lineEditScore)

        self.retranslateUi(ChoiceWindow)
        QtCore.QMetaObject.connectSlotsByName(ChoiceWindow)

    def retranslateUi(self, ChoiceWindow):
        _translate = QtCore.QCoreApplication.translate
        ChoiceWindow.setWindowTitle(_translate("ChoiceWindow", "选择内场"))
        self.label.setText(_translate("ChoiceWindow", "请选择内场"))
        self.pushButtonQL.setText(_translate("ChoiceWindow", "青龙"))
        self.pushButtonBH.setText(_translate("ChoiceWindow", "白虎"))
        self.pushButtonZQ.setText(_translate("ChoiceWindow", "朱雀"))
        self.pushButtonXW.setText(_translate("ChoiceWindow", "玄武"))
        self.label_2.setText(_translate("ChoiceWindow", "按ESC键退出当前练习"))
        self.label_3.setText(_translate("ChoiceWindow", "正确："))
        self.label_4.setText(_translate("ChoiceWindow", "错误："))
        self.Score.setText(_translate("ChoiceWindow", "得分："))
