# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CompleteImage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompleteImage(object):
    def setupUi(self, CompleteImage):
        CompleteImage.setObjectName("CompleteImage")
        CompleteImage.resize(670, 765)
        self.layoutWidget = QtWidgets.QWidget(CompleteImage)
        self.layoutWidget.setGeometry(QtCore.QRect(480, 190, 121, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonQL = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQL.sizePolicy().hasHeightForWidth())
        self.pushButtonQL.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonQL.setFont(font)
        self.pushButtonQL.setDefault(True)
        self.pushButtonQL.setObjectName("pushButtonQL")
        self.verticalLayout.addWidget(self.pushButtonQL)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonBH = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBH.sizePolicy().hasHeightForWidth())
        self.pushButtonBH.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonBH.setFont(font)
        self.pushButtonBH.setObjectName("pushButtonBH")
        self.verticalLayout.addWidget(self.pushButtonBH)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButtonZQ = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonZQ.sizePolicy().hasHeightForWidth())
        self.pushButtonZQ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonZQ.setFont(font)
        self.pushButtonZQ.setObjectName("pushButtonZQ")
        self.verticalLayout.addWidget(self.pushButtonZQ)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButtonXW = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonXW.sizePolicy().hasHeightForWidth())
        self.pushButtonXW.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButtonXW.setFont(font)
        self.pushButtonXW.setObjectName("pushButtonXW")
        self.verticalLayout.addWidget(self.pushButtonXW)
        self.graphicsView1 = QtWidgets.QGraphicsView(CompleteImage)
        self.graphicsView1.setGeometry(QtCore.QRect(120, 50, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView1.sizePolicy().hasHeightForWidth())
        self.graphicsView1.setSizePolicy(sizePolicy)
        self.graphicsView1.setStyleSheet("border-image: url(:/star/QL1.jpg);")
        self.graphicsView1.setObjectName("graphicsView1")
        self.graphicsView2 = QtWidgets.QGraphicsView(CompleteImage)
        self.graphicsView2.setGeometry(QtCore.QRect(120, 280, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView2.sizePolicy().hasHeightForWidth())
        self.graphicsView2.setSizePolicy(sizePolicy)
        self.graphicsView2.setStyleSheet("border-image: url(:/star/QL2.jpg);")
        self.graphicsView2.setObjectName("graphicsView2")
        self.graphicsView3 = QtWidgets.QGraphicsView(CompleteImage)
        self.graphicsView3.setGeometry(QtCore.QRect(120, 510, 256, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView3.sizePolicy().hasHeightForWidth())
        self.graphicsView3.setSizePolicy(sizePolicy)
        self.graphicsView3.setStyleSheet("border-image: url(:/star/QL3.jpg);")
        self.graphicsView3.setObjectName("graphicsView3")

        self.retranslateUi(CompleteImage)
        QtCore.QMetaObject.connectSlotsByName(CompleteImage)

    def retranslateUi(self, CompleteImage):
        _translate = QtCore.QCoreApplication.translate
        CompleteImage.setWindowTitle(_translate("CompleteImage", "完整星图"))
        self.pushButtonQL.setText(_translate("CompleteImage", "青龙"))
        self.pushButtonBH.setText(_translate("CompleteImage", "白虎"))
        self.pushButtonZQ.setText(_translate("CompleteImage", "朱雀"))
        self.pushButtonXW.setText(_translate("CompleteImage", "玄武"))
import Images_rc
